### ISSUE TITLE
CRC for IDs other than 1

### ISSUE THREAD

**Issue by nethawk2** [riogrande75/sdm630poller#1]
Hello,
my SDM630 is at ID 2.
I assume, i have to modify beside the ID field the CRChi and CRClo too.
How must i change these values ?
Thank you

//                ID      READ                                    ADDR      CRChi     CRClo
fwrite($fp, chr(0x01).chr(0x04).chr(0x00).chr(0x00).chr(0x00).chr(0x4c).chr(0xf1).chr(0xff));

**Comment by riogrande75** [comment]
Sorry for the (VERY) late reply. Obviously I was not notified.
You can use this site for CRC calculation: [https://crccalc.com](url)
For verifying I use this site: [https://rapidscada.net/modbus/](url)
In your case, the request must look like this: `02040000004CF1CC`
